[build]
  functions = "functions"
  command = "pip install -r requirements.txt && python functions/wsgi.py"

[functions]
  directory = "functions"
  external_node_modules = ["flask", "flask-mail", "numpy", "pandas", "joblib", "python-dotenv"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/wsgi"
  status = 200
